// Only export the things that are actually needed, cut out everything else
export { TextureLoader } from "three/src/loaders/TextureLoader.js";
export { FontLoader } from "three/src/loaders/FontLoader";
export { Color } from "three/src/math/Color.js";
export { DataTexture } from "three/src/textures/DataTexture";
export * from "three/src/constants.js";
export { MathUtils as Math } from "three/src/math/MathUtils";
export { Mesh } from "three/src/objects/Mesh.js";
export { OrthographicCamera } from "three/src/cameras/OrthographicCamera.js";
export { PlaneGeometry, PlaneBufferGeometry } from "three/src/geometries/PlaneGeometry.js";
export { Scene } from "three/src/scenes/Scene.js";
export { ShaderMaterial } from "three/src/materials/ShaderMaterial.js";
export { UniformsUtils } from "three/src/renderers/shaders/UniformsUtils.js";
export { Group } from "three/src/objects/Group.js";
export { Vector3 } from "three/src/math/Vector3.js";
export { Vector2 } from "three/src/math/Vector2.js";
export { Clock } from "three/src/core/Clock.js";
export { Layers } from "three/src/core/Layers.js";

export { WebGLRenderer } from "three/src/renderers/WebGLRenderer.js";
// export { ShaderLib } from "three/src/renderers/shaders/ShaderLib.js";
// export { UniformsLib } from "three/src/renderers/shaders/UniformsLib.js";
// export { ShaderChunk } from "three/src/renderers/shaders/ShaderChunk.js";
// export { LineSegments } from "three/src/objects/LineSegments.js";
// export { Line } from "three/src/objects/Line.js";
// export { CubeTexture } from "three/src/textures/CubeTexture.js";
// export { CanvasTexture } from "three/src/textures/CanvasTexture.js";
export { SphereGeometry, SphereBufferGeometry } from "three/src/geometries/SphereGeometry.js";
// export { BoxGeometry, BoxBufferGeometry } from "three/src/geometries/BoxGeometry.js";
// export { ConeGeometry, ConeBufferGeometry } from "three/src/geometries/ConeGeometry.js";
// export { CylinderGeometry, CylinderBufferGeometry } from "three/src/geometries/CylinderGeometry.js";
// export { CircleGeometry, CircleBufferGeometry } from "three/src/geometries/CircleGeometry.js";
// export { RingGeometry, RingBufferGeometry } from "three/src/geometries/RingGeometry.js";
// export { EdgesGeometry } from "three/src/geometries/EdgesGeometry.js";
// export { Material } from "three/src/materials/Material.js";
// export { MeshPhongMaterial } from "three/src/materials/MeshPhongMaterial.js";
// export { MeshPhysicalMaterial } from "three/src/materials/MeshPhysicalMaterial.js";
export { MeshBasicMaterial } from "three/src/materials/MeshBasicMaterial.js";
export { PointsMaterial } from "three/src/materials/PointsMaterial";
export { Points } from "three/src/objects/Points.js";
export { MeshNormalMaterial } from "three/src/materials/MeshNormalMaterial.js";
export { TextGeometry, TextBufferGeometry } from "three/src/geometries/TextGeometry.js";
export { MeshStandardMaterial } from "three/src/materials/MeshStandardMaterial.js";
export { WebGLRenderTarget } from "three/src/renderers/WebGLRenderTarget.js";

// export { LineDashedMaterial } from "three/src/materials/LineDashedMaterial.js";
// export { SpriteMaterial } from "three/src/materials/SpriteMaterial.js";
// export { LineBasicMaterial } from "three/src/materials/LineBasicMaterial.js";
export { Texture } from "three/src/textures/Texture.js";
// export { Sprite } from "three/src/objects/Sprite.js";
// export { SpotLightShadow } from "three/src/lights/SpotLightShadow.js";
// export { SpotLight } from "three/src/lights/SpotLight.js";
// export { SpotLightHelper } from "three/src/helpers/SpotLightHelper.js";
// export { CameraHelper } from "three/src/helpers/CameraHelper.js";
export { PointLight } from "three/src/lights/PointLight.js";
export { DirectionalLight } from "three/src/lights/DirectionalLight.js";
export { AmbientLight } from "three/src/lights/AmbientLight.js";
// export { LightShadow } from "three/src/lights/LightShadow.js";
export { PerspectiveCamera } from "three/src/cameras/PerspectiveCamera.js";
export { BufferGeometry } from "three/src/core/BufferGeometry.js";
// export { Geometry } from "three/src/core/Geometry.js";
export * from "three/src/core/BufferAttribute.js";
// export { Face3 } from "three/src/core/Face3.js";
// export { Object3D } from "three/src/core/Object3D.js";
export { Raycaster } from "three/src/core/Raycaster.js";
// export { Triangle } from "three/src/math/Triangle.js";
// export { Spherical } from "three/src/math/Spherical.js";
// export { Cylindrical } from "three/src/math/Cylindrical.js";
// export { Plane } from "three/src/math/Plane.js";
// export { Frustum } from "three/src/math/Frustum.js";
// export { Sphere } from "three/src/math/Sphere.js";
// export { Ray } from "three/src/math/Ray.js";
// export { Matrix4 } from "three/src/math/Matrix4.js";
// export { Matrix3 } from "three/src/math/Matrix3.js";
// export { Box3 } from "three/src/math/Box3.js";
// export { Box2 } from "three/src/math/Box2.js";
// export { Line3 } from "three/src/math/Line3.js";
// export { Euler } from "three/src/math/Euler.js";
// export { Vector4 } from "three/src/math/Vector4.js";
// export { Quaternion } from "three/src/math/Quaternion.js";
// export { GridHelper } from "three/src/helpers/GridHelper.js";
// export { AxesHelper } from "three/src/helpers/AxesHelper.js";
// export { InstancedBufferGeometry } from "three/src/core/InstancedBufferGeometry.js";
// export { InstancedInterleavedBuffer } from "three/src/core/InstancedInterleavedBuffer.js";
// export { InterleavedBufferAttribute } from "three/src/core/InterleavedBufferAttribute.js";
// export { WireframeGeometry } from "three/src/geometries/WireframeGeometry.js";
